# Generated by Django 5.1.4 on 2025-03-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_photo",
            new_name="avatar",
        ),
    ]
