# Generated by Django 5.1.4 on 2025-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_room_category_alter_room_owner 2"),
        ("rooms", "0007_alter_room_amenities 2"),
        ("rooms", "0007_alter_room_amenities"),
    ]

    operations = []
