# Generated by Django 5.1.4 on 2025-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0003_alter_experience_category_alter_experience_host 2"),
        ("experiences", "0003_alter_experience_category_alter_experience_host"),
    ]

    operations = []
