# Generated by Django 5.1.4 on 2024-12-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiences", "0002_experience_category_alter_perk_description_and_more"),
        ("medias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vedio",
            name="experience",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="experiences.experience"
            ),
        ),
    ]
