# Generated by Django 5.1.4 on 2025-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0004_alter_photo_experience_alter_photo_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="file",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
