# Generated by Django 5.1.4 on 2025-03-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0005_alter_photo_file_alter_video_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="descprition",
            new_name="description",
        ),
    ]
