# Generated by Django 5.1.4 on 2025-02-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_experience_alter_review_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="name",
            new_name="user",
        ),
    ]
