# Generated by Django 5.1.4 on 2025-03-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more 2"),
        ("bookings", "0002_alter_booking_experience_alter_booking_room_and_more"),
    ]

    operations = []
